### ISSUE TITLE
Glow lichen crash

### ISSUE THREAD

**Issue by powerbute** [etil2jz/Mirai#11]
When you press bonemeal on glow lichen, the server crashes. Very easy to fix! Add to class GlowLichenBlock imports
`import static alternate.current.util.BlockUtil.DIRECTIONS;`

Crash report:
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 01.02.2022, 11:22
Description: Exception in server tick loop

java.lang.NoSuchFieldError: DIRECTIONS
	at net.minecraft.world.level.block.GlowLichenBlock.lambda$isValidBonemealTarget$1(GlowLichenBlock.java:55)
	at net.minecraft.world.item.BoneMealItem.growCrop(BoneMealItem.java:76)
	at net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:48)
	at net.minecraft.world.item.BoneMealItem.useOn(BoneMealItem.java:39)
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:329)
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:602)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1855)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:164)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
To fix, you just need to add an import.
---------------------------------------------------------------------------------------

**Comment by etil2jz** [comment]
Will fix as soon as I have free time
