### ISSUE TITLE
Failed to rename

### ISSUE THREAD

**Issue by Auriny** [etil2jz/Mirai#22]
When I downloaded Mirai, I noticed that strange errors of this kind began to appear on the server

```
[20:45:58 ERROR]: Failed to rename
java.nio.file.NoSuchFileException: ./world/playerdata/cadcf331-15ad-395d-aa55-05dc4677555f.dat -> ./world/playerdata/cadcf331-15ad-395d-aa55-05dc4677555f.dat_old
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:477) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at net.minecraft.Util$4.getAsBoolean(Util.java:547) ~[?:?]
        at net.minecraft.Util.executeInSequence(Util.java:612) ~[?:?]
        at net.minecraft.Util.runWithRetries(Util.java:623) ~[?:?]
        at net.minecraft.Util.safeReplaceOrMoveFile(Util.java:648) ~[?:?]
        at net.minecraft.Util.safeReplaceFile(Util.java:639) ~[?:?]
        at net.minecraft.Util.safeReplaceFile(Util.java:635) ~[?:?]
        at net.minecraft.world.level.storage.PlayerDataStorage.lambda$save$0(PlayerDataStorage.java:48) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:45:58 WARN]: Failed to execute rename ./world/playerdata/cadcf331-15ad-395d-aa55-05dc4677555f.dat to ./world/playerdata/cadcf331-15ad-395d-aa55-05dc4677555f.dat_old
[20:45:58 ERROR]: Failed to create backup ./world/playerdata/cadcf331-15ad-395d-aa55-05dc4677555f.dat_old, retrying 0/10
```

how to fix?
pl list: 
`Plugins (27): About_me, AdvancedBan, ajLeaderboards, ArmedArmorStands, AuthMe, Chatty, Chunky, CoreProtect, CoreProtectTNT, EasyWhitelist*, eHideTags, FarmControl, GSit, InventoryRollbackPlus, InvisibleItemFrames, LuckPerms, MyCommand, OpenInv, PlaceholderAPI, PlasmoVoice, ProtocolLib, RHLeafDecay, SkinsRestorer, TAB, Vault, Vulcan, WorldsColor`

**Comment by powerbute** [comment]
I assume that if this only happens with this server core, then this patch is most likely to blame.
0022-New-NBT-cache.patch
