### ISSUE TITLE
Can't start compiled core

### ISSUE THREAD

**Issue by zxcqirara** [etil2jz/Mirai#30]
```
PS C:\mirai-serv> java -jar .\mirai-paperclip-1.18.2-R0.1-SNAPSHOT-reobf.jar nogui
Downloading mojang_1.18.2.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.3+7-LTS) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[16:50:52 ERROR]: Failed to load properties from file: server.properties
[16:50:52 INFO]: [STDERR]: java.lang.IncompatibleClassChangeError: Expecting non-static method 'java.lang.String net.minecraft.server.dedicated.DedicatedServerProperties.c(java.lang.String)'
[16:50:52 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerProperties.<init>(DedicatedServerProperties.java:130)
[16:50:52 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerProperties.fromFile(DedicatedServerProperties.java:137)
[16:50:52 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerSettings.<init>(DedicatedServerSettings.java:19)
[16:50:52 INFO]: [STDERR]:      at net.minecraft.server.Main.main(Main.java:110)
[16:50:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.Main.main(Main.java:297)
[16:50:52 INFO]: [STDERR]:      at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
[16:50:52 INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by en0tuk** [comment]
https://github.com/FabricMC/tiny-remapper/issues/87

**Comment by en0tuk** [comment]
> [FabricMC/tiny-remapper#87](https://github.com/FabricMC/tiny-remapper/issues/87)

![image](https://user-images.githubusercontent.com/71115913/172870399-b565ff92-1fbf-4faa-8068-709c7ddc5fed.png)
