### ISSUE TITLE
Warn-Error that occurred to me only in Mirai [1.19 last build]

### ISSUE THREAD

**Issue by XionioXMaster** [etil2jz/Mirai#36]
**I also found a problem with AI MythicMobs**

[13:56:27 ERROR]: [STDERR] [net.minecraft.world.entity.EntityLiving] [NAN-HEALTH] be291e57-6cbb-4d8a-936a-9435a29b80d6 had NaN health set
[13:56:27 WARN]: [MythicMobs] Failed to construct AI pathfinder lookatplayers
[13:56:27 WARN]: java.lang.IllegalStateException: Cannot add sublisteners after listening range was set!
[13:56:27 WARN]:        at me.jellysquid.**mods.lithium**.common.entity.tracker.nearby.NearbyEntityListenerMulti.addListener(NearbyEntityListenerMulti.java:18)
[13:56:27 WARN]:        at net.minecraft.world.entity.Entity.addListener(Entity.java:175)
[13:56:27 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalLookAtPlayer.<init>(PathfinderGoalLookAtPlayer.java:59)
[13:56:27 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalLookAtPlayer.<init>(PathfinderGoalLookAtPlayer.java:36)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.core.volatilecode.v1_19_R1.ai.goals.LookAtPlayersGoal.create(LookAtPlayersGoal.java:26)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.core.volatilecode.v1_19_R1.VolatileAIHandlerImpl.addPathfinderGoals(VolatileAIHandlerImpl.java:264)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.core.skills.mechanics.RunAIGoalSelectorMechanic.cast(RunAIGoalSelectorMechanic.java:51)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.core.skills.SkillMechanic.executeNoTargetSkill(SkillMechanic.java:545)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeSkills$6(SkillMechanic.java:490)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[13:56:27 WARN]:        at MythicMobs-5.1.0-SNAPSHOT 4194 .jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[13:56:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:56:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:56:27 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[13:56:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:459)
[13:56:27 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1430)
[13:56:27 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1198)
[13:56:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304)
[13:56:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Sometimes a similar error may occur in the ModelEngine, I used to use SSSpigot before, this was not**

### 13:59:21 WARN]: [ModelEngine] **Plugin ModelEngine vR2.5.2** generated an exception while executing task 467
java.lang.NullPointerException: Cannot invoke "com.ticxo.modelengine.api.animation.Queryable.getQueryID()" because "<parameter1>" is null
        at com.ticxo.modelengine.api.animation.Query.addQuery(Query.java:23) ~[model-engine-r2_5_2.jar:?]
        at com.ticxo.modelengine.animation.MEAnimationInterpreter.getFramePosition(MEAnimationInterpreter.java:21) ~[model-engine-r2_5_2.jar:?]
        at com.ticxo.modelengine.model.part.MEBasePartEntity.tick(MEBasePartEntity.java:84) ~[model-engine-r2_5_2.jar:?]
        at com.ticxo.modelengine.model.MEActiveModel.tick(MEActiveModel.java:38) ~[model-engine-r2_5_2.jar:?]
        at com.ticxo.modelengine.model.MEModeledEntity.tick(MEModeledEntity.java:83) ~[model-engine-r2_5_2.jar:?]
        at com.ticxo.modelengine.manager.MEModelRunnable.run(MEModelRunnable.java:48) ~[model-engine-r2_5_2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[mirai-1.19.jar:git-Mirai-28d706c]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[mirai-1.19.jar:git-Mirai-28d706c]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[mirai-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by XionioXMaster** [comment]
It doesn't seem to be solved without a keg of beer.

**Comment by F1rsi** [comment]
Try Pufferfish

**Comment by XionioXMaster** [comment]
> ‎Попробуйте рыбу фугу‎

там всё работает

**Comment by F1rsi** [comment]
Okay

**Comment by etil2jz** [comment]
As a multi threaded entity tracker is now present, the patch affecting MythicMobs will be dropped as it became useless
